apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "arc-dashboard.serviceAccountName" . }}
  labels:
    {{- include "arc-dashboard.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadIdentity.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.workloadIdentity.tenantId | quote }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
