{{- if not .Values.persistence.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "arc-dashboard.fullname" . }}
  labels:
    {{- include "arc-dashboard.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.persistence.retainOnDelete }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
{{- end }}
