apiVersion: v2
name: arc-dashboard
description: Singleton Azure Arc Observability Dashboard deployment for Azure Kubernetes Service
type: application
version: 1.0.2
appVersion: "1.0.2"
kubeVersion: ">=1.27.0-0"
keywords:
  - azure
  - arc
  - aks
  - operations
